### ISSUE TITLE
checkMMD

### ISSUE THREAD

**Issue by hevgyrt** [steingod/solrindexing#33]
Do we need the check_mmd method in the MMD4SolR class? Since a MMD compliance checker is integrated in the MMD repository.

**Comment by steingod** [comment]
I think  it is good to have a slightly less restrictive checker embedded, else we won't be able to ingest harvested records. Isn't it laos checking e.g. date specifications? I think it should check availability of some core elements, consistency of dates and geographical elements etc. The external checker is more restrictive since it relies on the schema and that wouldn't work.
