### ISSUE TITLE
Use of related_dataset list for a parent entry

### ISSUE THREAD

**Issue by ferrighi** [steingod/solrindexing#41]
Evaluate if a list of children should be provided for a parent entry. 

Currently this information is not used by services using solr, but it might be used in pycsw or other tools. 

If this information is kept in solr, the software should be updated: using the -i option for indexing, children are correctly appended to the parent, while using the -d option (to index a full directory) the children list is overwritten, thus only the last indexed child is present in the parent list.

**Comment by steingod** [comment]
Could it be that the reason why parent records aren't properly updated is that since every child require the parent to be updated this would require either always_commit or waiting 20 minutes for each child?

**Comment by ferrighi** [comment]
Considering that Drupal is not using the list of children belonging to a parent and that we still have the isParent:true to identify a parent, I would suggest we remove the list update from within the parent record. @magnarem do you agree or see any issues?

**Comment by magnarem** [comment]
For me I do not see any issue with this. Go ahead!

**Comment by steingod** [comment]
While implementing this I just came to think that I don't understand how isParent is set if we are not updating parents. Setting isChild is pretty straightforward, but is actually isParent used?

**Comment by magnarem** [comment]
I will try to describe how it works, both during indexing and searching.

When indexing:
1.  A document is read, and if it does NOT have related_dataset, type=parent, it will be indexed with dataset_type=Level-1 and isParent=false.
2. If the document have related_dataset, type=parent, it will be indexed with dataset_type=Level-2 and isChild=true, and the uuid of related_dataset are stored in a list for later lookup.
3. The indexing tool will then look for the parent uuid, in the index, in the current batch, or store it for lookup later in the indexing, since this document might not have been indexed yet. When the document with the uuid is found, it is set to isParent=true.
4. Datasets that is not a parent will just be dataset_type=Level-1 and isParent=false

So by looking at a parent document in solr, the only way we know it is a parent is that it have isParent=true.

Then to get a list of the children that are children of that parent, we do a query for all other datasets that have isChild=true and related_dataset=uuid of the that parent.

So in the index a parent have no pointer to its children, but the children always knows what is the parent. So every time I find a document with isParent=true, I search for all datasets that have the related_dataset=uuid where uuid is the uuid of the parent.

I hope this makes some sense.

**Comment by steingod** [comment]
I think this is implemented now and will close this.
